apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: g38-ingest-vs
  namespace: g38
spec:
  gateways:
  - istio-system/devqa-istio-ingressgateway-inner
  hosts:
  - g38.svc.cluster.local
  tcp:
  - route:
    - destination:
        host: ingest.g38-dev.svc.cluster.local
        port:
          number: 9095
